### ISSUE TITLE
Add support for Go language

### ISSUE THREAD

**Issue by nikivdev** [Pustur/calamity-vscode#2]
I really love this theme and thank you for making and sharing it. 

I would love to add support for Go language however I am not quite sure how I can go about that. If you have the time, it would be awesome if it could be implemented, if not, I can try look into it but I am not sure of where to start.

Thank you for any help.

**Comment by Pustur** [comment]
Hey nikita,

Thanks for the kind words.
I never used Go but i will look into it and see if i can integrate it in this theme. 👍

**Comment by Pustur** [comment]
@nikitavoloboev 

So, I took a look at Go (I checked out some of your repositories to find sample files that I could test) and the theme right off the bat [looks pretty good](https://user-images.githubusercontent.com/13663338/30822250-69d6023c-a228-11e7-98c1-6d12ad005711.png).

I noticed that some things (like variables used somewhere outside of their declaration) cannot be colored because [vscode doesn't assign them a scope](https://user-images.githubusercontent.com/13663338/30823528-bf498b54-a22c-11e7-961d-60cbc2c5f3d6.jpg).

(to see what TM scopes are attached to a particular word, just open the command palette (CMD+SHIFT+P) and write "Inspect TM Scopes")

I'm going to close the issue for now, but if you find some words that are not properly colorized feel free to report them here 😉

**Comment by nikivdev** [comment]
Thank you @Pustur 

I was actually going to say that, the theme already looks really good and I love it. It's just that in README you didn't mention Go so I thought perhaps there were some things missing. I am still new to Go so I can't give a detailed response on what is missing but so far it's been pretty awesome. 🙂
